---
title: "data_wrangling_i"
author: "Shaocong Zhang"
date: "10/3/2021"
output:
  html_document: default
  pdf_document: default
---
I'm an R Markdown document! 

```{r}
library(tidyverse)
```

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
samp = rnorm(100)
length(samp)
```

# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.

```{r}
getwd()
```

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
spec(litters_data)
```

```{r}
names(litters_data)
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

```{r}
litters_data
tail(litters_data, 5)
```

```{r}
skimr::skim(litters_data)
```

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  skip = 10, col_names = FALSE)
spec(litters_data)
head(litters_data)
```

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```
```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = "ccddiiii"
)
litters_data
```

```{r}
pups.data = read_csv(file = "./data_import_examples/FAS_pups.csv", col_types = "ciiiii")
spec(pups.data)
head(pups.data)
names(pups.data)
pups.data = janitor::clean_names(pups.data)
names(pups.data)
skimr::skim(pups.data)
```


```{r}
library(readxl)
mlb11_data = read_excel("data_import_examples/mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)
```

```{r}
library(haven)
pulse_data = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```

```{r}
#pups_base = read.csv("./data_import_examples/FAS_pups.csv")
#pups_readr = read_csv("./data_import_examples/FAS_pups.csv")

#View(pups_base)
#View(pups_readr)

#pups_base
#pups_readr

#pups_base$S
#pups_readr$S
```
