---
title: "Data Manipulation with dplyr"
author: "Shaocong Zhang"
date: "10/3/2021"
output: html_document
---

```{r}
library(tidyverse)
options(tibble.print_min = 3)

litters_data = read_csv("./data_import_examples/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data_import_examples/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, -pups_survive)
```
```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```


```{r}
select(litters_data, starts_with("gd"))
```

```{r}
select(litters_data, litter_number, pups_survive, everything())
```

```{r}
relocate(litters_data, litter_number, pups_survive)
```
```{r}
select(pups_data, litter_number, sex, pd_ears)
```

```{r}
filter(pups_data, sex == 1)
filter(pups_data, sex == 2, pd_walk < 11)
```

```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

```{r}
mutate(pups_data, pivot_minus7 = pd_pivot - 7)
mutate(pups_data, pd_sum = pd_ears + pd_eyes + pd_pivot + pd_walk)
```


```{r}
head(arrange(litters_data, group, pups_born_alive), 10)
```
```{r}
read_csv("./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>% 
  filter(sex == 1) %>% 
  select(-pd_ears) %>% 
  mutate(pd_pivot_gt7 = pd_pivot > 7)
```





